name: Deploy to Windows Server

on:
  push:
    branches:
      - main   # შეცვალე თუ სხვა ბრენჩზე გინდა!

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy files to Windows Server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.WINDOWS_SSH_KEY }}
        port: 22
        source: "."
        target: "C:/Users/gmaisuradze-adm/deploy_folder"   # შეცვალე შენს საჭიროებებზე!

